language: php

services:
    - docker

sudo: false

dist: trusty

cache:
    directories:
        - $HOME/.composer/cache

install: composer update $COMPOSER_FLAGS

matrix:
    include:
        -
            php: 7.4
        -
            php: 7.4
            env: COMPOSER_FLAGS='--prefer-lowest'
        -
            php: nightly
            env: COMPOSER_FLAGS='--ignore-platform-reqs'
    allow_failures:
        - php: nightly

before_script:
    - docker run --rm -d -p 11300:11300 --name beanstalkd schickling/beanstalkd

script:
    - vendor/bin/phpunit
    - vendor/bin/phpspec run

after_script:
    - docker stop beanstalkd
